-- /tmp/migrate-order-status.sql
-- Remap existing Order + OrderStatusHistory rows from old statuses to new ones.
UPDATE "Order" SET orderStatus = CASE orderStatus
  WHEN 'PENDING_PAYMENT' THEN 'PLACED'
  WHEN 'RESTAURANT_ACCEPTED' THEN 'APPROVED'
  WHEN 'PREPARING' THEN 'APPROVED'
  WHEN 'READY_FOR_PICKUP' THEN 'APPROVED'
  WHEN 'PICKED_UP' THEN 'APPROVED'
  WHEN 'OUT_FOR_DELIVERY' THEN 'APPROVED'
  WHEN 'PAYMENT_FAILED' THEN 'CANCELLED'
  WHEN 'REJECTED_BY_RESTAURANT' THEN 'CANCELLED'
  ELSE orderStatus
END WHERE orderStatus IN ('PENDING_PAYMENT','RESTAURANT_ACCEPTED','PREPARING','READY_FOR_PICKUP','PICKED_UP','OUT_FOR_DELIVERY','PAYMENT_FAILED','REJECTED_BY_RESTAURANT');

UPDATE "OrderStatusHistory" SET fromStatus = CASE fromStatus
  WHEN 'PENDING_PAYMENT' THEN 'PLACED'
  WHEN 'RESTAURANT_ACCEPTED' THEN 'APPROVED'
  WHEN 'PREPARING' THEN 'APPROVED'
  WHEN 'READY_FOR_PICKUP' THEN 'APPROVED'
  WHEN 'PICKED_UP' THEN 'APPROVED'
  WHEN 'OUT_FOR_DELIVERY' THEN 'APPROVED'
  WHEN 'PAYMENT_FAILED' THEN 'CANCELLED'
  WHEN 'REJECTED_BY_RESTAURANT' THEN 'CANCELLED'
  ELSE fromStatus
END WHERE fromStatus IN ('PENDING_PAYMENT','RESTAURANT_ACCEPTED','PREPARING','READY_FOR_PICKUP','PICKED_UP','OUT_FOR_DELIVERY','PAYMENT_FAILED','REJECTED_BY_RESTAURANT');

UPDATE "OrderStatusHistory" SET toStatus = CASE toStatus
  WHEN 'PENDING_PAYMENT' THEN 'PLACED'
  WHEN 'RESTAURANT_ACCEPTED' THEN 'APPROVED'
  WHEN 'PREPARING' THEN 'APPROVED'
  WHEN 'READY_FOR_PICKUP' THEN 'APPROVED'
  WHEN 'PICKED_UP' THEN 'APPROVED'
  WHEN 'OUT_FOR_DELIVERY' THEN 'APPROVED'
  WHEN 'PAYMENT_FAILED' THEN 'CANCELLED'
  WHEN 'REJECTED_BY_RESTAURANT' THEN 'CANCELLED'
  ELSE toStatus
END WHERE toStatus IN ('PENDING_PAYMENT','RESTAURANT_ACCEPTED','PREPARING','READY_FOR_PICKUP','PICKED_UP','OUT_FOR_DELIVERY','PAYMENT_FAILED','REJECTED_BY_RESTAURANT');
